/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface IAnime {
  anime_id: IAnimeId;
  anime_name: IAnimeName[];
}

export type IAnimeId = string;

export type IAnimeName = string;

export interface IAnimeRaw {
  anime_id: IAnimeId;
  anime_name: string;
}
