/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface IEmoji {
  command: string;
  emoji_id: string;
  src: string;
  type: IEmojiType | 'img' | 'dec';
}

export type IEmojiType = 'img' | 'dec';
