/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { ISong } from '.';

export interface IClientData {
  admin: boolean;
  avatar:
    | IGameAvatar
    | 'Zero Two'
    | 'AE86'
    | 'Misaka'
    | 'Eva Unit One'
    | 'Homura'
    | 'Alphonse'
    | 'Horo'
    | 'Madoka'
    | 'Lelouch'
    | 'Miyu'
    | 'Rawr'
    | 'Pikachu'
    | 'Eren'
    | 'Judai'
    | 'Yugi';
  host: boolean;
  username: string;
}

export type IGameAvatar =
  | 'Zero Two'
  | 'AE86'
  | 'Misaka'
  | 'Eva Unit One'
  | 'Homura'
  | 'Alphonse'
  | 'Horo'
  | 'Madoka'
  | 'Lelouch'
  | 'Miyu'
  | 'Rawr'
  | 'Pikachu'
  | 'Eren'
  | 'Judai'
  | 'Yugi';

export interface IGameChatMessage {
  admin: boolean;
  avatar:
    | IGameAvatar
    | 'Zero Two'
    | 'AE86'
    | 'Misaka'
    | 'Eva Unit One'
    | 'Homura'
    | 'Alphonse'
    | 'Horo'
    | 'Madoka'
    | 'Lelouch'
    | 'Miyu'
    | 'Rawr'
    | 'Pikachu'
    | 'Eren'
    | 'Judai'
    | 'Yugi';
  repeat: boolean;
  sid: string;
  text: string;
  username: string;
}

export interface IGameGuess {
  anime?: string | '' | null;
  title?: string | '' | null;
}

export interface IGameLoginData {
  avatar:
    | IGameAvatar
    | 'Zero Two'
    | 'AE86'
    | 'Misaka'
    | 'Eva Unit One'
    | 'Homura'
    | 'Alphonse'
    | 'Horo'
    | 'Madoka'
    | 'Lelouch'
    | 'Miyu'
    | 'Rawr'
    | 'Pikachu'
    | 'Eren'
    | 'Judai'
    | 'Yugi';
  username: string;
}

export type IGameMode = 'normal' | 'balanced' | 'balanced_plus' | 'shiritori';

export interface IGamePlayer {
  admin: boolean;
  avatar:
    | IGameAvatar
    | 'Zero Two'
    | 'AE86'
    | 'Misaka'
    | 'Eva Unit One'
    | 'Homura'
    | 'Alphonse'
    | 'Horo'
    | 'Madoka'
    | 'Lelouch'
    | 'Miyu'
    | 'Rawr'
    | 'Pikachu'
    | 'Eren'
    | 'Judai'
    | 'Yugi';
  guess: IGameGuess;
  host: boolean;
  score: number;
  scoreColor: INotificationColor | 'success' | 'warning' | 'error';
  sid: string;
  username: string;
}

export interface IGameSettings {
  duplicate: boolean;
  gameMode: IGameMode | 'normal' | 'balanced' | 'balanced_plus' | 'shiritori';
  guessTime: number;
  songCount: number;
  users: string[];
}

export interface IGameState {
  currentSong: ISong;
  currentSongCount: number;
  maxSongCount: number;
  playing: boolean;
}

export type INotificationColor = 'success' | 'warning' | 'error';
