const SHARED_EVENTS = {
  AUTHENTICATE: 'AUTHENTICATE',
  SYSTEM_NOTIFICATION: 'SYSTEM_NOTIFICATION',
  UPDATE_SONG_LIST: 'UPDATE_SONG_LIST',
  UPDATE_ANIME_LIST: 'UPDATE_ANIME_LIST',
  UPDATE_SONG_TITLE_LIST: 'UPDATE_SONG_TITLE_LIST',
  UPDATE_USER_LISTS: 'UPDATE_USER_LISTS',
  RELOAD_SONG_LIST_DATA: 'RELOAD_SONG_LIST_DATA',
  JOIN_SONG_LIST: 'JOIN_SONG_LIST',
  LEAVE_ALL_ROOMS: 'LEAVE_ALL_ROOMS',
  EDIT_USER_LIST: 'EDIT_USER_LIST',
  GET_ROOM_LIST: 'GET_ROOM_LIST',
  UPDATE_ROOM_LIST: 'UPDATE_ROOM_LIST',
  NEW_GAME_ROOM: 'NEW_GAME_ROOM',
  JOIN_GAME_ROOM: 'JOIN_GAME_ROOM',
  GAME_CHAT: 'GAME_CHAT',
  UPDATE_GAME_CHAT: 'UPDATE_GAME_CHAT',
  GET_GAME_SETTINGS: 'GET_GAME_SETTINGS',
  UPDATE_GAME_SETTINGS: 'UPDATE_GAME_SETTINGS',
  EDIT_GAME_SETTINGS: 'EDIT_GAME_SETTINGS'
}

export {
  SHARED_EVENTS
}
