const STORE_SOCKET_EVENTS = {
  UPDATE_STORE_CLIENT_DATA: 'UPDATE_STORE_CLIENT_DATA',
  UPDATE_STORE_SONG_LIST: 'UPDATE_STORE_SONG_LIST',
  UPDATE_STORE_ANIME_LIST: 'UPDATE_STORE_ANIME_LIST',
  UPDATE_STORE_SONG_TITLES: 'UPDATE_STORE_SONG_TITLES',
  UPDATE_STORE_ANIME_NAMES: 'UPDATE_STORE_ANIME_NAMES',
  UPDATE_STORE_USER_SONG_LIST: 'UPDATE_STORE_USER_SONG_LIST',
  UPDATE_STORE_USER_LIST: 'UPDATE_STORE_USER_LIST',
  UPDATE_STORE_EMOJI_LIST: 'UPDATE_STORE_EMOJI_LIST'
};

const CLIENT_TO_SERVER_EVENTS = {
  AUTHORIZE_USER: 'AUTHORIZE_USER',
  ADMIN_NEW_USER: 'ADMIN_NEW_USER',
  ADMIN_EDIT_USER: 'ADMIN_EDIT_USER',
  ADMIN_DELETE_USER: 'ADMIN_DELETE_USER',
  UPDATE_USER_SETTINGS: 'UPDATE_USER_SETTINGS',
  ADD_USER_SONGS: 'ADD_USER_SONGS',
  REMOVE_USER_SONGS: 'REMOVE_USER_SONGS',
  ADMIN_NEW_ANIME: 'ADMIN_NEW_ANIME',
  ADMIN_EDIT_ANIME: 'ADMIN_EDIT_ANIME',
  ADMIN_DELETE_ANIME: 'ADMIN_DELETE_ANIME',
  ADMIN_NEW_SONG: 'ADMIN_NEW_SONG',
  ADMIN_EDIT_SONG: 'ADMIN_EDIT_SONG',
  ADMIN_DELETE_SONG: 'ADMIN_DELETE_SONG'
};

const SERVER_TO_CLIENT_EVENTS = {
  SYSTEM_NOTIFICATION: 'SYSTEM_NOTIFICATION'
};

const SOCKET_EVENTS = {
  CONNECT: 'connect',
  DISCONNECT: 'disconnect',

  ...CLIENT_TO_SERVER_EVENTS,
  ...SERVER_TO_CLIENT_EVENTS,
  ...STORE_SOCKET_EVENTS
};

export { SOCKET_EVENTS };
