version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "server"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "monthly"

  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "client"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "shared-resources"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "monthly"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"

  # Enable version updates for github actions
  - package-ecosystem: "github-actions"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
