version: '3'
services:
  amq_server:
    container_name: amq_server
    restart: unless-stopped
    build:
      context: '.'
      dockerfile: './server/Dockerfile'
    expose:
      - 3001
    volumes:
      - ./server/data/:/home/aq_server/server/data
      - ./server/log/:/home/aq_server/server/log
    env_file:
      - config.env
    logging:
      options:
        max-size: 50m
    networks:
      shared_net:

networks:
  shared_net:
