services:
  amq_server:
    container_name: amq_server
    restart: unless-stopped
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    volumes:
      - ./server/data/primary:/home/aq_server/server/data/primary
      - ./server/data/secondary:/home/aq_server/server/data/secondary
      - ./server/log/:/home/aq_server/server/log
    env_file:
      - server/config.env
    ports:
      - "3000:3000"
    logging:
      options:
        max-size: 50m
