version: '3'
services:
  amq_server:
    container_name: amq_server
    restart: unless-stopped
    build:
      context: './server/'
      dockerfile: 'Dockerfile'
    volumes:
      - ./server/data/:/home/aq_server/data
      - ./server/log/:/home/aq_server/log
    env_file:
      - server/config.env
    network_mode: host
    logging:
      options:
        max-size: 50m
