version: '3'
services:
  amq_server:
    container_name: amq_server
    restart: unless-stopped
    build:
      context: './server/'
      dockerfile: 'Dockerfile'
    ports:
      - 3000:3000
    volumes:
      - ./server/data/:/home/aq_server/data
      - ./server/log/:/home/aq_server/log
      - ./server/data-backup/:/home/aq_server/data-backup
    env_file:
      - server/config.env
    logging:
      options:
        max-size: 50m
