const LOCAL_STORAGE_CONSTANTS = {
  DARK_THEME: 'DARK_THEME',
  GAME_SERVER: 'GAME_SERVER',
  AQ_USERNAME: 'AQ_USERNAME',
  AQ_AVATAR: 'AQ_AVATAR',
  AQ_VOLUME: 'AQ_VOLUME',
  OAUTH_STATE: 'OAUTH_STATE'
};

const CLIENT_CONSTANTS = {
  SONG_LIST_EDIT_TABLE_HEIGHT: 'calc(100vh - 252px)'
};

const SONG_LIST_EDIT_MODE = {
  ADD: 'add',
  REMOVE: 'remove',
  NONE: 'none'
};

export { LOCAL_STORAGE_CONSTANTS, CLIENT_CONSTANTS, SONG_LIST_EDIT_MODE };
