const CLIENT_EVENTS = Object.freeze({
  REGISTER_SEND_NOTIFICATION: 'REGISTER_SEND_NOTIFICATION',
  REGISTER_OPEN_DIALOG: 'REGISTER_OPEN_DIALOG',
  SYSTEM_NOTIFICATION: 'SYSTEM_NOTIFICATION',
  OPEN_DIALOG: 'OPEN_DIALOG'
});

export { CLIENT_EVENTS };
