const ROUTES = {
  LOGIN: 'LOGIN',
  LOBBY: 'LOBBY',
  USER_SETTINGS: 'USER_SETTINGS',
  SONG_LIST_EDIT: 'SONG_LIST_EDIT',
  USER_EDIT: 'USER_EDIT',
  ANIME_EDIT: 'ANIME_EDIT',
  SONG_EDIT: 'SONG_EDIT',
  EMOJI_EDIT: 'EMOJI_EDIT',
  GAME_ROOMS: 'GAME_ROOMS',
  MAIN_GAME: 'MAIN_GAME',
  BOT_MESSAGE_EDIT: 'BOT_MESSAGE_EDIT'
} as const;

const DIALOG_ROUTES = {
  LOGIN_SETTINGS: 'LOGIN_SETTINGS',
  USER_EDIT: 'USER_EDIT',
  ANIME_EDIT: 'ANIME_EDIT',
  SONG_EDIT: 'SONG_EDIT',
  EMOJI_EDIT: 'EMOJI_EDIT',
  NEW_GAME_ROOM: 'NEW_GAME_ROOM',
  MAIN_GAME_SETTINGS: 'MAIN_GAME_SETTINGS',
  MAIN_GAME_SONG_PICKER: 'MAIN_GAME_SONG_PICKER',
  ADMIN_PANEL: 'ADMIN_PANEL',
  BOT_MESSAGE_EDIT: 'BOT_MESSAGE_EDIT'
} as const;

export { ROUTES, DIALOG_ROUTES };
