import {SHARED_EVENTS} from '../../assets/shared/events'

const MUTATIONS = {
  CHANGE_THEME: 'CHANGE_THEME',
  CHANGE_DIALOG_VIEW: 'CHANGE_DIALOG_VIEW',
  CHANGE_VIEW: 'CHANGE_VIEW',
  SOCKET_UPDATE_SONG_LIST: `SOCKET_${SHARED_EVENTS.UPDATE_SONG_LIST}`,
  SOCKET_UPDATE_ANIME_LIST: `SOCKET_${SHARED_EVENTS.UPDATE_ANIME_LIST}`,
  UPDATE_SONG_LIST_CURRENT_PAGE: 'UPDATE_SONG_LIST_CURRENT_PAGE',
  UPDATE_SONG_LIST_ANIME_FILTER: 'UPDATE_SONG_LIST_ANIME_FILTER'
}

export {
  MUTATIONS
}
