const LOCAL_STORAGE_CONSTANTS = {
  DARK_THEME: 'DARK_THEME',
  GAME_SERVER: 'GAME_SERVER',
  AQ_VOLUME: 'AQ_VOLUME',
  OAUTH_STATE: 'OAUTH_STATE',
  DATA_VERSION: 'DATA_VERSION',
  SONG_LIST: 'SONG_LIST',
  ANIME_LIST: 'ANIME_LIST',
  ANIME_NAMES: 'ANIME_NAMES',
  SONG_TITLES: 'SONG_TITLES',
  EMOJI_LIST: 'EMOJI_LIST',
  USER_EDIT_TABLE_ITEMS_PER_PAGE: 'USER_EDIT_TABLE_ITEMS_PER_PAGE',
  SONG_STATS_EDIT_TABLE_ITEMS_PER_PAGE: 'SONG_STATS_EDIT_TABLE_ITEMS_PER_PAGE',
  SONG_LIST_EDIT_TABLE_ITEMS_PER_PAGE: 'SONG_LIST_EDIT_TABLE_ITEMS_PER_PAGE',
  SONG_EDIT_TABLE_ITEMS_PER_PAGE: 'SONG_EDIT_TABLE_ITEMS_PER_PAGE',
  MUSIC_PLAYER_TABLE_ITEMS_PER_PAGE: 'MUSIC_PLAYER_TABLE_ITEMS_PER_PAGE',
  MAIN_GAME_SONG_PICKER_ITEMS_PER_PAGE: 'MAIN_GAME_SONG_PICKER_ITEMS_PER_PAGE',
  EMOJI_EDIT_TABLE_ITEMS_PER_PAGE: 'EMOJI_EDIT_TABLE_ITEMS_PER_PAGE',
  BOT_MESSAGE_EDIT_TABLE_ITEMS_PER_PAGE: 'BOT_MESSAGE_EDIT_TABLE_ITEMS_PER_PAGE',
  ANIME_EDIT_TABLE_ITEMS_PER_PAGE: 'ANIME_EDIT_TABLE_ITEMS_PER_PAGE'
} as const;

const CLIENT_CONSTANTS = {
  SONG_LIST_EDIT_TABLE_HEIGHT: 'calc(100vh - 262px)',
  ADMIN_TABLE_HEIGHT: 'calc(100vh - 202px)',
  PAGE_HEIGHT: 'calc(100vh - 72px)',
  GAME_SONG_PICKER_TABLE_HEIGHT: '400px',
  MUSIC_PLAYER_TABLE_HEIGHT: 'calc(100vh - 442px)',
  NAV_BAR_HEIGHT: '40',
  MAIN_CONTAINER_HEIGHT: 'calc(100vh - 40px)',
  TABLE_ACTION_WIDTH: '120px'
};

const SONG_LIST_EDIT_MODE = {
  ADD: 'add',
  REMOVE: 'remove',
  NONE: 'none'
};

const DATABASE_EDIT_MODE = {
  NEW: 'new',
  EDIT: 'edit',
  DELETE: 'delete'
};

const CLIENT_VERSION = `${import.meta.env.VITE_CLIENT_VERSION}`;
const ROOT_URL_PATH = '/';

export { LOCAL_STORAGE_CONSTANTS, CLIENT_CONSTANTS, SONG_LIST_EDIT_MODE, DATABASE_EDIT_MODE, CLIENT_VERSION, ROOT_URL_PATH };
