const CLIENT_EVENTS = {
  REGISTER_SEND_NOTIFICATION: 'REGISTER_SEND_NOTIFICATION',
  REGISTER_OPEN_DIALOG: 'REGISTER_OPEN_DIALOG',
  REGISTER_CHANGE_VOLUME_NORMAL_VIDEO: 'REGISTER_CHANGE_VOLUME_NORMAL_VIDEO',
  REGISTER_CHANGE_VOLUME_YOUTUBE_VIDEO: 'REGISTER_CHANGE_VOLUME_YOUTUBE_VIDEO',
  OPEN_DIALOG: 'OPEN_DIALOG',
  CHANGE_VOLUME: 'CHANGE_VOLUME'
}

export {
  CLIENT_EVENTS
}
