const ROUTES = {
  LOGIN: 'LOGIN',
  LOBBY: 'LOBBY',
  SONG_LIST: 'SONG_LIST',
  ROOM_LIST: 'ROOM_LIST',
  GAME_ROOM: 'GAME_ROOM',
  ANIME_EDIT: 'ANIME_EDIT',
  SONG_EDIT: 'SONG_EDIT',
  EMOJI_EDIT: 'EMOJI_EDIT'
}

const DIALOG_ROUTES = {
  LOGIN_SETTINGS: 'LOGIN_SETTINGS',
  NEW_ROOM: 'NEW_ROOM',
  GAME_ROOM_SETTINGS: 'GAME_ROOM_SETTINGS',
  NEW_ANIME_DIALOG: 'NEW_ANIME_DIALOG',
  EDIT_ANIME_DIALOG: 'EDIT_ANIME_DIALOG',
  DELETE_ANIME_DIALOG: 'DELETE_ANIME_DIALOG',
  EDIT_SONG_DIALOG: 'EDIT_SONG_DIALOG',
  NEW_SONG_DIALOG: 'NEW_SONG_DIALOG',
  DELETE_SONG_DIALOG: 'DELETE_SONG_DIALOG',
  ADMIN: 'ADMIN'
}

export {
  ROUTES,
  DIALOG_ROUTES
}
