import { z } from 'zod';
import { ClientData, NotificationColor, SystemNotification } from './client';
import { Song, SongId, SongTitle, SongType } from './song';
import { Anime, AnimeId, AnimeName } from './anime';
import { Avatar, DiscordId, User, UserId } from './user';
import { Emoji, EmojiId } from './emoji';

export type ClientDataType = z.infer<typeof ClientData>;
export type NotificationColorType = z.infer<typeof NotificationColor>;
export type SystemNotificationType = z.infer<typeof SystemNotification>;
export type AvatarType = z.infer<typeof Avatar>;
export type SongTypeType = z.infer<typeof SongType>;
export type SongTitleType = z.infer<typeof SongTitle>;
export type AnimeNameType = z.infer<typeof AnimeName>;
export type AnimeIdType = z.infer<typeof AnimeId>;
export type SongType = z.infer<typeof Song>;
export type AnimeType = z.infer<typeof Anime>;
export type SongIdType = z.infer<typeof SongId>;
export type UserType = z.infer<typeof User>;
export type UserIdType = z.infer<typeof UserId>;
export type DiscordIdType = z.infer<typeof DiscordId>;
export type EmojiType = z.infer<typeof Emoji>;
export type EmojiIdType = z.infer<typeof EmojiId>;
