const ROUTES = {
  LOGIN: 'LOGIN',
  LOBBY: 'LOBBY',
  USER_SETTINGS: 'USER_SETTINGS',
  SONG_LIST_EDIT: 'SONG_LIST_EDIT'
};

const DIALOG_ROUTES = {
  LOGIN_SETTINGS: 'LOGIN_SETTINGS'
};

export { ROUTES, DIALOG_ROUTES };
