const ROUTES = {
  LOGIN: 'LOGIN',
  LOBBY: 'LOBBY',
  USER_SETTINGS: 'USER_SETTINGS',
  SONG_LIST_EDIT: 'SONG_LIST_EDIT',
  USER_EDIT: 'USER_EDIT'
};

const DIALOG_ROUTES = {
  LOGIN_SETTINGS: 'LOGIN_SETTINGS',
  NEW_USER: 'NEW_USER'
};

export { ROUTES, DIALOG_ROUTES };
