const ROUTES = {
  LOGIN: 'LOGIN',
  LOBBY: 'LOBBY',
  SONG_LIST: 'SONG_LIST',
  ROOM_LIST: 'ROOM_LIST',
  GAME_ROOM: 'GAME_ROOM'
}

const DIALOG_ROUTES = {
  LOGIN_SETTINGS: 'LOGIN_SETTINGS',
  NEW_ROOM: 'NEW_ROOM'
}

export {
  ROUTES,
  DIALOG_ROUTES
}
