const ROUTES = {
  LOGIN: 'LOGIN',
  LOBBY: 'LOBBY',
  SONG_LIST: 'SONG_LIST',
  ROOM_LIST: 'ROOM_LIST',
  GAME_ROOM: 'GAME_ROOM',
  ANIME_LIST_EDIT: 'ANIME_LIST_EDIT'
}

const DIALOG_ROUTES = {
  LOGIN_SETTINGS: 'LOGIN_SETTINGS',
  NEW_ROOM: 'NEW_ROOM',
  GAME_ROOM_SETTINGS: 'GAME_ROOM_SETTINGS'
}

export {
  ROUTES,
  DIALOG_ROUTES
}
