name: CI

env:
  CACHE_NAME: node_modules

on: [ pull_request ]

jobs:
  check-formatting:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Runner setup
        uses: ./.github/actions/runner-setup/

      - name: Check formatting
        run: pnpm format:check

  test-build-typescript:
    name: Test build typescript
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Runner setup
        uses: ./.github/actions/runner-setup/

      - name: Test build typescript
        run: |
          touch client/.env
          echo VITE_DISCORD_CLIENT_ID=${{ secrets.VITE_DISCORD_CLIENT_ID }} >> client/.env
          echo VITE_REDIRECT_URL=${{ secrets.VITE_REDIRECT_URL }} >> client/.env
          echo VITE_CLIENT_VERSION=${{ env.GITHUB_SHA_SHORT }} >> client/.env
          pnpm build

  test-build-server-docker:
    name: Test build server docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Runner setup
        uses: ./.github/actions/runner-setup/

      - name: Test build server
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          platforms: linux/amd64,linux/arm64
          build-args: DOCKER_SERVER_VERSION=${{ github.ref_name }}

