name: CI

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          pushd client
          pnpm install
          popd
          pushd server
          pnpm install
          popd

      - name: Test build client
        run: |
          cd client
          touch .env
          echo VITE_DISCORD_CLIENT_ID=${{ secrets.VITE_DISCORD_CLIENT_ID }} >> .env
          echo VITE_REDIRECT_URL=${{ secrets.VITE_REDIRECT_URL }} >> .env
          export VITE_CLIENT_VERSION=$(git rev-parse --short "$GITHUB_SHA")
          echo VITE_CLIENT_VERSION=${{ env.VITE_CLIENT_VERSION }} >> .env
          pnpm run build
