name: CI

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: make install

      - name: Check formatting
        run: make check-format

      - name: Test build client
        run: |
          cd client
          touch .env
          echo VITE_DISCORD_CLIENT_ID=${{ secrets.VITE_DISCORD_CLIENT_ID }} >> .env
          echo VITE_REDIRECT_URL=${{ secrets.VITE_REDIRECT_URL }} >> .env
          export VITE_CLIENT_VERSION=$(git rev-parse --short "$GITHUB_SHA")
          echo VITE_CLIENT_VERSION=${{ env.VITE_CLIENT_VERSION }} >> .env
          make build

      - name: Test build server
        uses: docker/build-push-action@v5
        with:
          context: server
          push: false
          platforms: linux/amd64,linux/arm64
          build-args: DOCKER_SERVER_VERSION=${{ github.ref_name }}
